add tag

diff --git a/create_packages b/create_packages
--- a/create_packages
+++ b/create_packages
@@ -3,7 +3,11 @@
 
 ######################################################################
 
-VERSION="${1:-$(git describe --abbrev=0 --tags)}"
+VERSION="$(git describe --abbrev=0 --tags)"
+if [ -z "$VERSION" ];then
+   echo "ERROR: unable to find a tag"
+   exit 100
+fi
 
 ######################################################################
 ### HELPERS
